#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2017 Joyent, Inc.
#

#
# Run all sdc-system-tests.
#

if [ "$TRACE" != "" ]; then
    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail

PATH=/opt/smartdc/bin:/usr/node/bin:$PATH


#---- guard

if [[ ! -f "/lib/sdc/.sdc-test-no-production-data" ]]; then
    cat <<EOF
To run this test you must create the file:

    /lib/sdc/.sdc-test-no-production-data

after ensuring you have no production data on this SDC.
EOF
    exit 2
fi



#---- support functions

function fatal
{
    echo "$(basename $0): fatal error: $*"
    exit 1
}

function usage () {
    echo "Usage:"
    echo "  runtests [OPTIONS...]"
    echo ""
    echo "Options:"
    echo "  -h          Print this help and exit."
    echo "  -f FILTER   Filter pattern (substring match) for test files to run."
    echo "  -r REPOTER  The nodeunit reporter to use."
}


#---- mainline

start_time=$(date +%s)

TOP=$(cd $(dirname $0)/; pwd)
NODEUNIT=./node_modules/nodeunit/bin/nodeunit

# Options.
opt_test_pattern=
opt_reporter=default
while getopts "hf:r:" opt
do
    case "$opt" in
        h)
            usage
            exit 0
            ;;
        f)
            opt_test_pattern=$OPTARG
            ;;
        r)
            opt_reporter=$OPTARG
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

cd $TOP

# Setup a clean output dir.
OUTPUT_DIR=/var/tmp/systests
echo "# Setup a clean output dir ($OUTPUT_DIR)."
rm -rf $OUTPUT_DIR
mkdir -p $OUTPUT_DIR

echo ""
echo "# Run sdc-system-tests."
test_files=$(ls -1 test/*.test.js)
if [[ -n "$opt_test_pattern" ]]; then
    test_files=$(echo "$test_files" | grep "$opt_test_pattern" || true)
    echo "# Running filtered set of test files: $test_files"
fi
if [[ -n "$test_files" ]]; then
    PATH=$TOP/build/node/bin:$PATH $NODEUNIT --reporter=$opt_reporter $test_files \
        | tee $OUTPUT_DIR/sdc-system-tests.tap
fi

# TODO: add a runtests to sdc-designation.git that can take `-f FILTER`.
echo ""
echo "# Run sdc-designation tests."
(cd ./node_modules/dapi && ./node_modules/.bin/tape \
    test/*.test.js test/algorithms.test.js) \
    | tee $OUTPUT_DIR/sdc-designation.tap

echo ""
echo "# Run node-sdc-clients tests."
PATH=$TOP/build/node/bin:$PATH ./node_modules/sdc-clients/test/runtests \
    -f "$opt_test_pattern" \
    | tee $OUTPUT_DIR/node-sdc-clients.tap
