#!/bin/bash
#
# Rsync the build in this working copy to '/var/tmp/sdc-system-tests' in
# the GZ of the given HN.
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE=$1

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
else
    # Clean node_modules everytime.
    ssh $NODE rm -rf /var/tmp/sdc-system-tests/node_modules
fi

rsync -av ${TOP}/ \
    $NODE://var/tmp/sdc-system-tests/ \
    $extraOpts \
    --exclude .git/ \
    --exclude /deps/ \
    --exclude /doc/ \
    --exclude /tools/ \
    --exclude /tmp/
